declare namespace NodeJS {
  interface ProcessEnv {
    readonly ZWEB_API_BASE_URL: string
    readonly ZWEB_BUILDER_URL: string
    readonly ZWEB_CLOUD_URL: string
    readonly ZWEB_MARKET_URL: string
    readonly ZWEB_INSTANCE_ID: string
    readonly ZWEB_APP_VERSION: string
    readonly ZWEB_APP_ENV: string
    readonly ZWEB_CLOUD_USER_EMAIL: string
    readonly ZWEB_CLOUD_USER_PASSWORD: string
    readonly ZWEB_CLOUD_TEAM_IDENTITY: string
    readonly ZWEB_SUPABASE_KEY: string
    readonly ZWEB_S3_ACL: string
    readonly ZWEB_S3_REGION: string
    readonly ZWEB_S3_BASEURL: string
    readonly ZWEB_S3_BUCKETNAME: string
    readonly ZWEB_S3_ACCESSKEYID: string
    readonly ZWEB_S3_SECRETACCESSKEY: string
    readonly ZWEB_NEON_HOST: string
    readonly ZWEB_NEON_PORT: string
    readonly ZWEB_NEON_DATABASENAME: string
    readonly ZWEB_NEON_DATABASEPASSWORD: string
    readonly ZWEB_NEON_DATABASEUSERNAME: string
    readonly ZWEB_SMTP_HOST: string
    readonly ZWEB_SMTP_PASSWORD: string
    readonly ZWEB_SMTP_USERNAME: string
    readonly ZWEB_SMTP_PORT: string
    readonly ZWEB_TIDB_HOST: string
    readonly ZWEB_TIDB_PORT: string
    readonly ZWEB_TIDB_DATABASENAME: string
    readonly ZWEB_TIDB_DATABASEPASSWORD: string
    readonly ZWEB_TIDB_DATABASEUSERNAME: string
    readonly ZWEB_MSSQL_HOST: string
    readonly ZWEB_MSSQL_PORT: string
    readonly ZWEB_MSSQL_PASSWORD: string
    readonly ZWEB_MSSQL_USERNAME: string
    readonly ZWEB_MSSQL_DATABASENAME: string
    readonly ZWEB_MYSQL_HOST: string
    readonly ZWEB_MYSQL_PORT: string
    readonly ZWEB_MYSQL_DATABASENAME: string
    readonly ZWEB_MYSQL_DATABASEPASSWORD: string
    readonly ZWEB_MYSQL_DATABASEUSERNAME: string
    readonly ZWEB_REDIS_HOST: string
    readonly ZWEB_REDIS_PORT: string
    readonly ZWEB_REDIS_DATABASEPASSWORD: string
    readonly ZWEB_REDIS_DATABASEUSERNAME: string
    readonly ZWEB_ORACLE_HOST: string
    readonly ZWEB_ORACLE_NAME: string
    readonly ZWEB_ORACLE_PORT: string
    readonly ZWEB_ORACLE_PASSWORD: string
    readonly ZWEB_ORACLE_USERNAME: string
    readonly ZWEB_ORACLE_CONNECTIONTYPE: string
    readonly ZWEB_COUCHDB_HOST: string
    readonly ZWEB_COUCHDB_PORT: string
    readonly ZWEB_COUCHDB_PASSWORD: string
    readonly ZWEB_COUCHDB_USERNAME: string
    readonly ZWEB_MARIADB_HOST: string
    readonly ZWEB_MARIADB_PORT: string
    readonly ZWEB_MARIADB_DATABASENAME: string
    readonly ZWEB_MARIADB_DATABASEPASSWORD: string
    readonly ZWEB_MARIADB_DATABASEUSERNAME: string
    readonly ZWEB_RESTAPI_BASEURL: string
    readonly ZWEB_RESTAPI_AUTHENTICATION: string
    readonly ZWEB_APPWRITE_HOST: string
    readonly ZWEB_APPWRITE_APIKEY: string
    readonly ZWEB_APPWRITE_PROJECTID: string
    readonly ZWEB_APPWRITE_DATABASEID: string
    readonly ZWEB_FIREBASE_PROJECTID: string
    readonly ZWEB_FIREBASE_DATABASEURL: string
    readonly ZWEB_FIREBASE_PRIVATEKEY: string
    readonly ZWEB_POSTGRESQL_HOST: string
    readonly ZWEB_POSTGRESQL_PORT: string
    readonly ZWEB_POSTGRESQL_DATABASENAME: string
    readonly ZWEB_POSTGRESQL_DATABASEPASSWORD: string
    readonly ZWEB_POSTGRESQL_DATABASEUSERNAME: string
    readonly ZWEB_HUGGINGFACE_TOKEN: string
    readonly ZWEB_GOOGLESHEETS_AUTHENTICATION: string
    readonly ZWEB_GOOGLESHEETS_PRIVATEKEY: string
    readonly ZWEB_ELASTICSEARCH_HOST: string
    readonly ZWEB_ELASTICSEARCH_PORT: string
    readonly ZWEB_ELASTICSEARCH_PASSWORD: string
    readonly ZWEB_ELASTICSEARCH_USERNAME: string
  }
}
